<?php

/**
*
* Generated by DezDevTools @ 2016-09-22 21:29:30
*
* @author Ivan Gontarenko
* @licence MIT
*
*/

namespace AdminkaModels;

use AdminkaModels\Generated\Query\QueryBuilder_4088db6603a73135b738fb6d8d56a91a;

class UserRoleResourceQuery extends QueryBuilder_4088db6603a73135b738fb6d8d56a91a
{
    // write your code here
}