<?php

/**
*
* Generated by DezDevTools @ 2016-09-22 21:29:09
*
* @author Ivan Gontarenko
* @licence MIT
*
*/

namespace AdminkaModels;

use AdminkaModels\Generated\Query\QueryBuilder_93870af500d5f9847ec36181e34e7887;

class UserPermissionsQuery extends QueryBuilder_93870af500d5f9847ec36181e34e7887
{
    // write your code here
}