<?php

/**
 *
 * Generated by DezDevTools @ 2016-09-22 21:29:30
 *
 * @author Ivan Gontarenko
 * @licence MIT
 *
*/

namespace AdminkaModels;

use AdminkaModels\Generated\Entity\Entity_4088db6603a73135b738fb6d8d56a91a;

class UserRoleResource extends Entity_4088db6603a73135b738fb6d8d56a91a
{
    // write your code here
}