<?php

/**
 *
 * Generated by DezDevTools @ 2016-09-22 21:29:40
 *
 * @author Ivan Gontarenko
 * @licence MIT
 *
*/

namespace AdminkaModels;

use AdminkaModels\Generated\Entity\Entity_f6d0de1bebb4dca9eb6245d130892716;

class UserResources extends Entity_f6d0de1bebb4dca9eb6245d130892716
{
    // write your code here
}