<?php

/**
 *
 * Generated by DezDevTools @ 2016-09-22 21:28:25
 *
 * @author Ivan Gontarenko
 * @licence MIT
 *
*/

namespace AdminkaModels;

use AdminkaModels\Generated\Entity\Entity_dca58335a7fbd0d43e4146885e53d736;

class UserRoles extends Entity_dca58335a7fbd0d43e4146885e53d736
{
    // write your code here
}